import { FC } from "react";
import Title from "../UI/Title";
import { Figma, Code, Layout, Sliders } from "react-feather";
import Button from "../UI/Button";

interface FeaturesProps {}

const Features: FC<FeaturesProps> = ({}) => {
  return (
    <div className="mt-12 flex flex-col items-center bg-slate-200 text-slate-800 rounded-3xl">
      <Title size="small" className="mb-6 mt-12 sm:px-20 text-center">
        Packed with features to get you started!
      </Title>
      <div className="grid sm:grid-cols-1 lg:grid-cols-4 md:grid-cols-2 gap-10 justify-around mt-24 mb-24 px-12">
        <div className="px-6">
          <Figma size={48} className="mb-8" />
          <p className="text-xl font-semibold">Works with Figma</p>
          <p className="mt-4 font-normal opacity-80">
            Documint is a free plugin that you can get from the Figma community,
            it uses the free tier of the GPT-4 Engine. Consider donting to keep
            the project alive and kicking!
          </p>
        </div>
        <div className="px-6">
          <Code size={48} className="mb-8" />
          <p className="text-xl font-semibold">Dev Documentation</p>
          <p className="mt-4 font-normal opacity-80">
            Apart from the UI red-lining, Documint also generates comprehensive
            code documentation in ReactJS Markup that you can edit later. Never
            leave your developers in the dark!
          </p>
        </div>
        <div className="px-6">
          <Layout size={48} className="mb-8" />
          <p className="text-xl font-semibold">Auto Layout Ouput</p>
          <p className="mt-4 font-normal opacity-80">
            The output frame generated by Documint is fully auto layout so you
            don&apos;t have to bother with how it looks while editing. Just
            generate and edit quickly!
          </p>
        </div>
        <div className="px-6">
          <Sliders size={48} className="mb-8" />
          <p className="text-xl font-semibold">Configurable Properties</p>
          <p className="mt-4 font-normal opacity-80">
            The Documint builder asks for configureable properties to make your
            documentation more precise and valuable. Try tinkering and playing
            with the output!
          </p>
        </div>
      </div>
      <Button hasIcon icon="figma" className="mb-12">
        Try For Free
      </Button>
    </div>
  );
};

export default Features;
